export const AuditActionCode = {
  create: "CREATE",
  update: "UPDATE",
  submit: "SUBMIT",
  approve: "APPROVE",
  reject: "REJECT",
  archive: "ARCHIVE",
  void: "VOID",
  uploadAttachment: "UPLOAD_ATTACHMENT",
  downloadAttachment: "DOWNLOAD_ATTACHMENT",
  markFeePaid: "MARK_FEE_PAID",
  waiveFee: "WAIVE_FEE",
  cancelFee: "CANCEL_FEE",
  confirmReminder: "CONFIRM_REMINDER",
  configUpdate: "CONFIG_UPDATE",
  bootstrapAdmin: "BOOTSTRAP_ADMIN",
  login: "LOGIN",
  loginFailed: "LOGIN_FAILED",
  logout: "LOGOUT",
  sessionRevoked: "SESSION_REVOKED",
  authMeDenied: "AUTH_ME_DENIED",
  inviteCreated: "INVITE_CREATED",
  inviteResent: "INVITE_RESENT",
  inviteAccepted: "INVITE_ACCEPTED",
  inviteRevoked: "INVITE_REVOKED",
  passwordResetRequestedSelf: "PASSWORD_RESET_REQUESTED_SELF",
  passwordResetRequestedAdmin: "PASSWORD_RESET_REQUESTED_ADMIN",
  passwordResetConfirmed: "PASSWORD_RESET_CONFIRMED",
  passwordResetRevoked: "PASSWORD_RESET_REVOKED",
  passwordResetFailed: "PASSWORD_RESET_FAILED",
  credentialChanged: "CREDENTIAL_CHANGED",
} as const;

export type AuditActionCode =
  (typeof AuditActionCode)[keyof typeof AuditActionCode];
